// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: aluno.proto

package java_grpc;

public final class AlunoOuterClass {
  private AlunoOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AlunoIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:AlunoId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();
  }
  /**
   * Protobuf type {@code AlunoId}
   */
  public  static final class AlunoId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:AlunoId)
      AlunoIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use AlunoId.newBuilder() to construct.
    private AlunoId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private AlunoId() {
      id_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private AlunoId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return java_grpc.AlunoOuterClass.internal_static_AlunoId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return java_grpc.AlunoOuterClass.internal_static_AlunoId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              java_grpc.AlunoOuterClass.AlunoId.class, java_grpc.AlunoOuterClass.AlunoId.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof java_grpc.AlunoOuterClass.AlunoId)) {
        return super.equals(obj);
      }
      java_grpc.AlunoOuterClass.AlunoId other = (java_grpc.AlunoOuterClass.AlunoId) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static java_grpc.AlunoOuterClass.AlunoId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static java_grpc.AlunoOuterClass.AlunoId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(java_grpc.AlunoOuterClass.AlunoId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code AlunoId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:AlunoId)
        java_grpc.AlunoOuterClass.AlunoIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return java_grpc.AlunoOuterClass.internal_static_AlunoId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return java_grpc.AlunoOuterClass.internal_static_AlunoId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                java_grpc.AlunoOuterClass.AlunoId.class, java_grpc.AlunoOuterClass.AlunoId.Builder.class);
      }

      // Construct using java_grpc.AlunoOuterClass.AlunoId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return java_grpc.AlunoOuterClass.internal_static_AlunoId_descriptor;
      }

      @java.lang.Override
      public java_grpc.AlunoOuterClass.AlunoId getDefaultInstanceForType() {
        return java_grpc.AlunoOuterClass.AlunoId.getDefaultInstance();
      }

      @java.lang.Override
      public java_grpc.AlunoOuterClass.AlunoId build() {
        java_grpc.AlunoOuterClass.AlunoId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public java_grpc.AlunoOuterClass.AlunoId buildPartial() {
        java_grpc.AlunoOuterClass.AlunoId result = new java_grpc.AlunoOuterClass.AlunoId(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof java_grpc.AlunoOuterClass.AlunoId) {
          return mergeFrom((java_grpc.AlunoOuterClass.AlunoId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(java_grpc.AlunoOuterClass.AlunoId other) {
        if (other == java_grpc.AlunoOuterClass.AlunoId.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java_grpc.AlunoOuterClass.AlunoId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (java_grpc.AlunoOuterClass.AlunoId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:AlunoId)
    }

    // @@protoc_insertion_point(class_scope:AlunoId)
    private static final java_grpc.AlunoOuterClass.AlunoId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new java_grpc.AlunoOuterClass.AlunoId();
    }

    public static java_grpc.AlunoOuterClass.AlunoId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<AlunoId>
        PARSER = new com.google.protobuf.AbstractParser<AlunoId>() {
      @java.lang.Override
      public AlunoId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new AlunoId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<AlunoId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<AlunoId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public java_grpc.AlunoOuterClass.AlunoId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AlunoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Aluno)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string nome = 2;</code>
     */
    java.lang.String getNome();
    /**
     * <code>string nome = 2;</code>
     */
    com.google.protobuf.ByteString
        getNomeBytes();
  }
  /**
   * Protobuf type {@code Aluno}
   */
  public  static final class Aluno extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Aluno)
      AlunoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Aluno.newBuilder() to construct.
    private Aluno(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Aluno() {
      id_ = 0;
      nome_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Aluno(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nome_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return java_grpc.AlunoOuterClass.internal_static_Aluno_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return java_grpc.AlunoOuterClass.internal_static_Aluno_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              java_grpc.AlunoOuterClass.Aluno.class, java_grpc.AlunoOuterClass.Aluno.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int NOME_FIELD_NUMBER = 2;
    private volatile java.lang.Object nome_;
    /**
     * <code>string nome = 2;</code>
     */
    public java.lang.String getNome() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nome_ = s;
        return s;
      }
    }
    /**
     * <code>string nome = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNomeBytes() {
      java.lang.Object ref = nome_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nome_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getNomeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nome_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getNomeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nome_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof java_grpc.AlunoOuterClass.Aluno)) {
        return super.equals(obj);
      }
      java_grpc.AlunoOuterClass.Aluno other = (java_grpc.AlunoOuterClass.Aluno) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getNome()
          .equals(other.getNome());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NOME_FIELD_NUMBER;
      hash = (53 * hash) + getNome().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static java_grpc.AlunoOuterClass.Aluno parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static java_grpc.AlunoOuterClass.Aluno parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(java_grpc.AlunoOuterClass.Aluno prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Aluno}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Aluno)
        java_grpc.AlunoOuterClass.AlunoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return java_grpc.AlunoOuterClass.internal_static_Aluno_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return java_grpc.AlunoOuterClass.internal_static_Aluno_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                java_grpc.AlunoOuterClass.Aluno.class, java_grpc.AlunoOuterClass.Aluno.Builder.class);
      }

      // Construct using java_grpc.AlunoOuterClass.Aluno.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        nome_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return java_grpc.AlunoOuterClass.internal_static_Aluno_descriptor;
      }

      @java.lang.Override
      public java_grpc.AlunoOuterClass.Aluno getDefaultInstanceForType() {
        return java_grpc.AlunoOuterClass.Aluno.getDefaultInstance();
      }

      @java.lang.Override
      public java_grpc.AlunoOuterClass.Aluno build() {
        java_grpc.AlunoOuterClass.Aluno result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public java_grpc.AlunoOuterClass.Aluno buildPartial() {
        java_grpc.AlunoOuterClass.Aluno result = new java_grpc.AlunoOuterClass.Aluno(this);
        result.id_ = id_;
        result.nome_ = nome_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof java_grpc.AlunoOuterClass.Aluno) {
          return mergeFrom((java_grpc.AlunoOuterClass.Aluno)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(java_grpc.AlunoOuterClass.Aluno other) {
        if (other == java_grpc.AlunoOuterClass.Aluno.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getNome().isEmpty()) {
          nome_ = other.nome_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java_grpc.AlunoOuterClass.Aluno parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (java_grpc.AlunoOuterClass.Aluno) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object nome_ = "";
      /**
       * <code>string nome = 2;</code>
       */
      public java.lang.String getNome() {
        java.lang.Object ref = nome_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nome_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNomeBytes() {
        java.lang.Object ref = nome_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nome_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder setNome(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nome_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder clearNome() {
        
        nome_ = getDefaultInstance().getNome();
        onChanged();
        return this;
      }
      /**
       * <code>string nome = 2;</code>
       */
      public Builder setNomeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nome_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Aluno)
    }

    // @@protoc_insertion_point(class_scope:Aluno)
    private static final java_grpc.AlunoOuterClass.Aluno DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new java_grpc.AlunoOuterClass.Aluno();
    }

    public static java_grpc.AlunoOuterClass.Aluno getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Aluno>
        PARSER = new com.google.protobuf.AbstractParser<Aluno>() {
      @java.lang.Override
      public Aluno parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Aluno(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Aluno> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Aluno> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public java_grpc.AlunoOuterClass.Aluno getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AlunosOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Alunos)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Aluno alunos = 1;</code>
     */
    java.util.List<java_grpc.AlunoOuterClass.Aluno> 
        getAlunosList();
    /**
     * <code>repeated .Aluno alunos = 1;</code>
     */
    java_grpc.AlunoOuterClass.Aluno getAlunos(int index);
    /**
     * <code>repeated .Aluno alunos = 1;</code>
     */
    int getAlunosCount();
    /**
     * <code>repeated .Aluno alunos = 1;</code>
     */
    java.util.List<? extends java_grpc.AlunoOuterClass.AlunoOrBuilder> 
        getAlunosOrBuilderList();
    /**
     * <code>repeated .Aluno alunos = 1;</code>
     */
    java_grpc.AlunoOuterClass.AlunoOrBuilder getAlunosOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Alunos}
   */
  public  static final class Alunos extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Alunos)
      AlunosOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Alunos.newBuilder() to construct.
    private Alunos(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Alunos() {
      alunos_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Alunos(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                alunos_ = new java.util.ArrayList<java_grpc.AlunoOuterClass.Aluno>();
                mutable_bitField0_ |= 0x00000001;
              }
              alunos_.add(
                  input.readMessage(java_grpc.AlunoOuterClass.Aluno.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          alunos_ = java.util.Collections.unmodifiableList(alunos_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return java_grpc.AlunoOuterClass.internal_static_Alunos_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return java_grpc.AlunoOuterClass.internal_static_Alunos_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              java_grpc.AlunoOuterClass.Alunos.class, java_grpc.AlunoOuterClass.Alunos.Builder.class);
    }

    public static final int ALUNOS_FIELD_NUMBER = 1;
    private java.util.List<java_grpc.AlunoOuterClass.Aluno> alunos_;
    /**
     * <code>repeated .Aluno alunos = 1;</code>
     */
    public java.util.List<java_grpc.AlunoOuterClass.Aluno> getAlunosList() {
      return alunos_;
    }
    /**
     * <code>repeated .Aluno alunos = 1;</code>
     */
    public java.util.List<? extends java_grpc.AlunoOuterClass.AlunoOrBuilder> 
        getAlunosOrBuilderList() {
      return alunos_;
    }
    /**
     * <code>repeated .Aluno alunos = 1;</code>
     */
    public int getAlunosCount() {
      return alunos_.size();
    }
    /**
     * <code>repeated .Aluno alunos = 1;</code>
     */
    public java_grpc.AlunoOuterClass.Aluno getAlunos(int index) {
      return alunos_.get(index);
    }
    /**
     * <code>repeated .Aluno alunos = 1;</code>
     */
    public java_grpc.AlunoOuterClass.AlunoOrBuilder getAlunosOrBuilder(
        int index) {
      return alunos_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < alunos_.size(); i++) {
        output.writeMessage(1, alunos_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < alunos_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, alunos_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof java_grpc.AlunoOuterClass.Alunos)) {
        return super.equals(obj);
      }
      java_grpc.AlunoOuterClass.Alunos other = (java_grpc.AlunoOuterClass.Alunos) obj;

      boolean result = true;
      result = result && getAlunosList()
          .equals(other.getAlunosList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getAlunosCount() > 0) {
        hash = (37 * hash) + ALUNOS_FIELD_NUMBER;
        hash = (53 * hash) + getAlunosList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static java_grpc.AlunoOuterClass.Alunos parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static java_grpc.AlunoOuterClass.Alunos parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(java_grpc.AlunoOuterClass.Alunos prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Alunos}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Alunos)
        java_grpc.AlunoOuterClass.AlunosOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return java_grpc.AlunoOuterClass.internal_static_Alunos_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return java_grpc.AlunoOuterClass.internal_static_Alunos_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                java_grpc.AlunoOuterClass.Alunos.class, java_grpc.AlunoOuterClass.Alunos.Builder.class);
      }

      // Construct using java_grpc.AlunoOuterClass.Alunos.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAlunosFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (alunosBuilder_ == null) {
          alunos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          alunosBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return java_grpc.AlunoOuterClass.internal_static_Alunos_descriptor;
      }

      @java.lang.Override
      public java_grpc.AlunoOuterClass.Alunos getDefaultInstanceForType() {
        return java_grpc.AlunoOuterClass.Alunos.getDefaultInstance();
      }

      @java.lang.Override
      public java_grpc.AlunoOuterClass.Alunos build() {
        java_grpc.AlunoOuterClass.Alunos result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public java_grpc.AlunoOuterClass.Alunos buildPartial() {
        java_grpc.AlunoOuterClass.Alunos result = new java_grpc.AlunoOuterClass.Alunos(this);
        int from_bitField0_ = bitField0_;
        if (alunosBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            alunos_ = java.util.Collections.unmodifiableList(alunos_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.alunos_ = alunos_;
        } else {
          result.alunos_ = alunosBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof java_grpc.AlunoOuterClass.Alunos) {
          return mergeFrom((java_grpc.AlunoOuterClass.Alunos)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(java_grpc.AlunoOuterClass.Alunos other) {
        if (other == java_grpc.AlunoOuterClass.Alunos.getDefaultInstance()) return this;
        if (alunosBuilder_ == null) {
          if (!other.alunos_.isEmpty()) {
            if (alunos_.isEmpty()) {
              alunos_ = other.alunos_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureAlunosIsMutable();
              alunos_.addAll(other.alunos_);
            }
            onChanged();
          }
        } else {
          if (!other.alunos_.isEmpty()) {
            if (alunosBuilder_.isEmpty()) {
              alunosBuilder_.dispose();
              alunosBuilder_ = null;
              alunos_ = other.alunos_;
              bitField0_ = (bitField0_ & ~0x00000001);
              alunosBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getAlunosFieldBuilder() : null;
            } else {
              alunosBuilder_.addAllMessages(other.alunos_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        java_grpc.AlunoOuterClass.Alunos parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (java_grpc.AlunoOuterClass.Alunos) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java_grpc.AlunoOuterClass.Aluno> alunos_ =
        java.util.Collections.emptyList();
      private void ensureAlunosIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          alunos_ = new java.util.ArrayList<java_grpc.AlunoOuterClass.Aluno>(alunos_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          java_grpc.AlunoOuterClass.Aluno, java_grpc.AlunoOuterClass.Aluno.Builder, java_grpc.AlunoOuterClass.AlunoOrBuilder> alunosBuilder_;

      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public java.util.List<java_grpc.AlunoOuterClass.Aluno> getAlunosList() {
        if (alunosBuilder_ == null) {
          return java.util.Collections.unmodifiableList(alunos_);
        } else {
          return alunosBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public int getAlunosCount() {
        if (alunosBuilder_ == null) {
          return alunos_.size();
        } else {
          return alunosBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public java_grpc.AlunoOuterClass.Aluno getAlunos(int index) {
        if (alunosBuilder_ == null) {
          return alunos_.get(index);
        } else {
          return alunosBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public Builder setAlunos(
          int index, java_grpc.AlunoOuterClass.Aluno value) {
        if (alunosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlunosIsMutable();
          alunos_.set(index, value);
          onChanged();
        } else {
          alunosBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public Builder setAlunos(
          int index, java_grpc.AlunoOuterClass.Aluno.Builder builderForValue) {
        if (alunosBuilder_ == null) {
          ensureAlunosIsMutable();
          alunos_.set(index, builderForValue.build());
          onChanged();
        } else {
          alunosBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public Builder addAlunos(java_grpc.AlunoOuterClass.Aluno value) {
        if (alunosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlunosIsMutable();
          alunos_.add(value);
          onChanged();
        } else {
          alunosBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public Builder addAlunos(
          int index, java_grpc.AlunoOuterClass.Aluno value) {
        if (alunosBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAlunosIsMutable();
          alunos_.add(index, value);
          onChanged();
        } else {
          alunosBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public Builder addAlunos(
          java_grpc.AlunoOuterClass.Aluno.Builder builderForValue) {
        if (alunosBuilder_ == null) {
          ensureAlunosIsMutable();
          alunos_.add(builderForValue.build());
          onChanged();
        } else {
          alunosBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public Builder addAlunos(
          int index, java_grpc.AlunoOuterClass.Aluno.Builder builderForValue) {
        if (alunosBuilder_ == null) {
          ensureAlunosIsMutable();
          alunos_.add(index, builderForValue.build());
          onChanged();
        } else {
          alunosBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public Builder addAllAlunos(
          java.lang.Iterable<? extends java_grpc.AlunoOuterClass.Aluno> values) {
        if (alunosBuilder_ == null) {
          ensureAlunosIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, alunos_);
          onChanged();
        } else {
          alunosBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public Builder clearAlunos() {
        if (alunosBuilder_ == null) {
          alunos_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          alunosBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public Builder removeAlunos(int index) {
        if (alunosBuilder_ == null) {
          ensureAlunosIsMutable();
          alunos_.remove(index);
          onChanged();
        } else {
          alunosBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public java_grpc.AlunoOuterClass.Aluno.Builder getAlunosBuilder(
          int index) {
        return getAlunosFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public java_grpc.AlunoOuterClass.AlunoOrBuilder getAlunosOrBuilder(
          int index) {
        if (alunosBuilder_ == null) {
          return alunos_.get(index);  } else {
          return alunosBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public java.util.List<? extends java_grpc.AlunoOuterClass.AlunoOrBuilder> 
           getAlunosOrBuilderList() {
        if (alunosBuilder_ != null) {
          return alunosBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(alunos_);
        }
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public java_grpc.AlunoOuterClass.Aluno.Builder addAlunosBuilder() {
        return getAlunosFieldBuilder().addBuilder(
            java_grpc.AlunoOuterClass.Aluno.getDefaultInstance());
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public java_grpc.AlunoOuterClass.Aluno.Builder addAlunosBuilder(
          int index) {
        return getAlunosFieldBuilder().addBuilder(
            index, java_grpc.AlunoOuterClass.Aluno.getDefaultInstance());
      }
      /**
       * <code>repeated .Aluno alunos = 1;</code>
       */
      public java.util.List<java_grpc.AlunoOuterClass.Aluno.Builder> 
           getAlunosBuilderList() {
        return getAlunosFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          java_grpc.AlunoOuterClass.Aluno, java_grpc.AlunoOuterClass.Aluno.Builder, java_grpc.AlunoOuterClass.AlunoOrBuilder> 
          getAlunosFieldBuilder() {
        if (alunosBuilder_ == null) {
          alunosBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              java_grpc.AlunoOuterClass.Aluno, java_grpc.AlunoOuterClass.Aluno.Builder, java_grpc.AlunoOuterClass.AlunoOrBuilder>(
                  alunos_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          alunos_ = null;
        }
        return alunosBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Alunos)
    }

    // @@protoc_insertion_point(class_scope:Alunos)
    private static final java_grpc.AlunoOuterClass.Alunos DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new java_grpc.AlunoOuterClass.Alunos();
    }

    public static java_grpc.AlunoOuterClass.Alunos getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Alunos>
        PARSER = new com.google.protobuf.AbstractParser<Alunos>() {
      @java.lang.Override
      public Alunos parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Alunos(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Alunos> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Alunos> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public java_grpc.AlunoOuterClass.Alunos getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AlunoId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AlunoId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Aluno_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Aluno_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Alunos_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Alunos_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013aluno.proto\032\033google/protobuf/empty.pro" +
      "to\"\025\n\007AlunoId\022\n\n\002id\030\001 \001(\005\"!\n\005Aluno\022\n\n\002id" +
      "\030\001 \001(\005\022\014\n\004nome\030\002 \001(\t\" \n\006Alunos\022\026\n\006alunos" +
      "\030\001 \003(\0132\006.Aluno2\322\001\n\020CrudAlunoService\022\035\n\013C" +
      "reateAluno\022\006.Aluno\032\006.Aluno\022/\n\014GetAllAlun" +
      "os\022\026.google.protobuf.Empty\032\007.Alunos\022\034\n\010G" +
      "etAluno\022\010.AlunoId\032\006.Aluno\0221\n\013DeleteAluno" +
      "\022\010.AlunoId\032\026.google.protobuf.Empty\"\000\022\035\n\t" +
      "EditAluno\022\006.Aluno\032\006.Aluno\"\000B\013\n\tjava_grpc" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
        }, assigner);
    internal_static_AlunoId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AlunoId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AlunoId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_Aluno_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Aluno_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Aluno_descriptor,
        new java.lang.String[] { "Id", "Nome", });
    internal_static_Alunos_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Alunos_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Alunos_descriptor,
        new java.lang.String[] { "Alunos", });
    com.google.protobuf.EmptyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
